2022-07-28 04:41:11,499 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/python/flask/app/routes.py", line 25, in index
    return  render_template('index.html',title='Home Page',form=form,posts=posts)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/python/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/root/python/flask/app/templates/index.html", line 9, in block 'content'
    {{ form.post.label }}<br>
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'post'
2022-07-28 04:55:12,268 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 08:10:21,956 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 08:19:11,910 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 08:27:09,036 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 09:17:49,521 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 09:17:54,113 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/python/flask/app/routes.py", line 27, in index
    return  render_template('index.html',title='Home Page',form=form,posts=posts)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/python/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/root/python/flask/app/templates/index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-07-28 09:19:50,036 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 09:35:00,761 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 09:35:05,262 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/python/flask/app/routes.py", line 30, in index
    return  render_template('index.html',title='Home Page',form=form,
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/index.html", line 26, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-07-28 09:35:43,958 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 09:35:47,530 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/python/flask/app/routes.py", line 30, in index
    return  render_template('index.html',title='Home Page',form=form,
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/python/flask/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/python/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/root/python/flask/app/templates/index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-07-28 09:37:51,151 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 10:11:42,353 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 10:12:50,184 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-07-28 10:13:12,991 INFO: Microblog startup [in /root/python/flask/app/__init__.py:43]
2022-08-01 03:12:20,404 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 04:54:31,583 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 04:55:58,625 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 04:58:05,013 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:10:40,255 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:12:28,866 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
2022-08-01 07:13:09,182 INFO: Microblog startup [in /root/python/flask/app/__init__.py:45]
